/*
 * gush — the gnu-mac-utils shell.
 *
 * Classic Mac OS has no terminal, so this console application provides
 * one: a persistent prompt with every utility linked in as a builtin,
 * plus cd/exit/help. Pipes and redirection are emulated with temporary
 * files between builtins, since the OS has no processes to connect:
 *
 *     % sort "My Disk:words" | uniq -c > counts
 *
 * Syntax notes: tokens are separated by spaces ("|", "<", ">", ">>"
 * must be surrounded by spaces); double quotes group words so HFS paths
 * with spaces work.
 *
 * `gush -c "command line"` runs one command line and exits (used by the
 * test suite; also handy with LaunchAPPL).
 */
#include "gucompat.h"

#include <stdlib.h>
#include <string.h>

#ifdef GU_HOST
#include <unistd.h>
#endif

const char *gu_progname = "gush";

/* Builtin entry points, generated by shell/builtin_<tool>.c wrappers. */
int gu_true_main(int, char **);
int gu_false_main(int, char **);
int gu_echo_main(int, char **);
int gu_cat_main(int, char **);
int gu_head_main(int, char **);
int gu_tail_main(int, char **);
int gu_wc_main(int, char **);
int gu_sort_main(int, char **);
int gu_uniq_main(int, char **);
int gu_basename_main(int, char **);
int gu_dirname_main(int, char **);
int gu_pwd_main(int, char **);
int gu_ls_main(int, char **);
int gu_mkdir_main(int, char **);
int gu_rmdir_main(int, char **);
int gu_rm_main(int, char **);
int gu_mv_main(int, char **);
int gu_cp_main(int, char **);
int gu_touch_main(int, char **);
int gu_date_main(int, char **);
int gu_sleep_main(int, char **);
int gu_uname_main(int, char **);

typedef int (*gu_tool_fn)(int, char **);
static const struct {
    const char *name;
    gu_tool_fn fn;
} builtins[] = {
    { "true", gu_true_main },       { "false", gu_false_main },
    { "echo", gu_echo_main },       { "cat", gu_cat_main },
    { "head", gu_head_main },       { "tail", gu_tail_main },
    { "wc", gu_wc_main },           { "sort", gu_sort_main },
    { "uniq", gu_uniq_main },       { "basename", gu_basename_main },
    { "dirname", gu_dirname_main }, { "pwd", gu_pwd_main },
    { "ls", gu_ls_main },           { "mkdir", gu_mkdir_main },
    { "rmdir", gu_rmdir_main },     { "rm", gu_rm_main },
    { "mv", gu_mv_main },           { "cp", gu_cp_main },
    { "touch", gu_touch_main },     { "date", gu_date_main },
    { "sleep", gu_sleep_main },     { "uname", gu_uname_main },
};
#define NBUILTINS ((int)(sizeof(builtins) / sizeof(builtins[0])))

#define GUSH_TMP_A "gush-pipe-a.tmp"
#define GUSH_TMP_B "gush-pipe-b.tmp"
#define MAX_TOKENS 64
#define MAX_STAGES 8

static gu_tool_fn find_builtin(const char *name)
{
    int i;
    for (i = 0; i < NBUILTINS; i++)
        if (strcmp(builtins[i].name, name) == 0)
            return builtins[i].fn;
    return NULL;
}

static int tokenize(char *line, char **tok, int max)
{
    int n = 0;
    char *p = line;
    while (*p && n < max) {
        while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')
            p++;
        if (!*p)
            break;
        if (*p == '"') {
            p++;
            tok[n++] = p;
            while (*p && *p != '"')
                p++;
        } else {
            tok[n++] = p;
            while (*p && *p != ' ' && *p != '\t' && *p != '\r' && *p != '\n')
                p++;
        }
        if (*p)
            *p++ = '\0';
    }
    return n;
}

static int run_stage(gu_tool_fn fn, const char *name, int argc, char **argv,
                     const char *in_path, const char *out_path, int append)
{
    FILE *inf = NULL, *outf = NULL;
    int status;

    if (in_path) {
        inf = fopen(in_path, "r");
        if (!inf) {
            gu_warn("%s: cannot open input", in_path);
            return 1;
        }
        gu_set_in(inf);
    }
    if (out_path) {
        outf = fopen(out_path, append ? "a" : "w");
        if (!outf) {
            gu_warn("%s: cannot open output", out_path);
            if (inf)
                fclose(inf);
            gu_set_in(NULL);
            return 1;
        }
        gu_set_out(outf);
    }

    gu_getopt_reset();
    gu_progname = name;
    status = fn(argc, argv);
    gu_progname = "gush";

    gu_set_in(NULL);
    gu_set_out(NULL);
    if (inf)
        fclose(inf);
    if (outf)
        fclose(outf);
    return status;
}

/* Execute one command line. Returns the last stage's exit status. */
static int run_line(char *line)
{
    char *tok[MAX_TOKENS];
    int ntok = tokenize(line, tok, MAX_TOKENS);
    struct {
        char **argv;
        int argc;
    } stage[MAX_STAGES];
    char *argvbuf[MAX_TOKENS + MAX_STAGES];
    int nstages = 0;
    char *redir_in = NULL, *redir_out = NULL;
    int append = 0;
    int i, s, ai = 0;
    int status = 0;

    if (ntok == 0)
        return 0;

    /* Shell-level builtins. */
    if (strcmp(tok[0], "exit") == 0 || strcmp(tok[0], "quit") == 0)
        return -1;
    if (strcmp(tok[0], "help") == 0) {
        fprintf(gu_out(), "builtins: cd exit help");
        for (i = 0; i < NBUILTINS; i++)
            fprintf(gu_out(), " %s", builtins[i].name);
        fprintf(gu_out(), "\nsyntax: cmd [args] [| cmd ...] [< file] [> file | >> file]\n");
        return 0;
    }
    if (strcmp(tok[0], "cd") == 0) {
        int rc;
        if (ntok < 2) {
            gu_warn("usage: cd directory");
            return 1;
        }
        rc = gu_chdir(tok[1]);
        if (rc != GU_OK) {
            gu_warn("cd: %s: %s", tok[1], gu_strerror(rc));
            return 1;
        }
        return 0;
    }

    /* Split into pipeline stages, peeling off redirections. */
    stage[0].argv = &argvbuf[ai];
    stage[0].argc = 0;
    nstages = 1;
    for (i = 0; i < ntok; i++) {
        if (strcmp(tok[i], "|") == 0) {
            if (stage[nstages - 1].argc == 0) {
                gu_warn("syntax error near '|'");
                return 1;
            }
            argvbuf[ai++] = NULL;
            if (nstages == MAX_STAGES) {
                gu_warn("pipeline too long");
                return 1;
            }
            stage[nstages].argv = &argvbuf[ai];
            stage[nstages].argc = 0;
            nstages++;
        } else if (strcmp(tok[i], "<") == 0) {
            if (++i == ntok) {
                gu_warn("syntax error near '<'");
                return 1;
            }
            redir_in = tok[i];
        } else if (strcmp(tok[i], ">") == 0 || strcmp(tok[i], ">>") == 0) {
            append = tok[i][1] == '>';
            if (++i == ntok) {
                gu_warn("syntax error near '>'");
                return 1;
            }
            redir_out = tok[i];
        } else {
            stage[nstages - 1].argv[stage[nstages - 1].argc++] = tok[i];
            ai++;
        }
    }
    argvbuf[ai] = NULL;
    if (stage[nstages - 1].argc == 0) {
        gu_warn("syntax error: empty command");
        return 1;
    }

    /* Resolve all stages before running anything. */
    {
        gu_tool_fn fns[MAX_STAGES];
        for (s = 0; s < nstages; s++) {
            fns[s] = find_builtin(stage[s].argv[0]);
            if (!fns[s]) {
                gu_warn("%s: not a gush builtin (try 'help')", stage[s].argv[0]);
                return 127;
            }
        }
        for (s = 0; s < nstages; s++) {
            int last = (s == nstages - 1);
            const char *in_path = (s == 0) ? redir_in
                                : (s % 2 == 1) ? GUSH_TMP_A : GUSH_TMP_B;
            const char *out_path = !last ? ((s % 2 == 0) ? GUSH_TMP_A : GUSH_TMP_B)
                                 : redir_out;
            status = run_stage(fns[s], stage[s].argv[0],
                               stage[s].argc, stage[s].argv,
                               in_path, out_path, last && append);
        }
    }
    if (nstages > 1) {
        (void)gu_delete(GUSH_TMP_A);
        (void)gu_delete(GUSH_TMP_B);
    }
    return status;
}

int main(int argc, char **argv)
{
    static char line[GU_LINE_MAX];
    static char cwd[GU_PATH_MAX];
    int interactive;
    int status = 0;

    if (argc >= 3 && strcmp(argv[1], "-c") == 0) {
        strncpy(line, argv[2], sizeof(line) - 1);
        line[sizeof(line) - 1] = '\0';
        status = run_line(line);
        return status < 0 ? 0 : status;
    }

#ifdef GU_MACOS
    interactive = 1;
    printf("gush — gnu-mac-utils shell. Type 'help' for commands, 'exit' to quit.\n");
#else
    interactive = isatty(0);
#endif

    for (;;) {
        if (interactive) {
            if (gu_getcwd(cwd, sizeof(cwd)) != GU_OK)
                strcpy(cwd, "?");
            printf("%s %% ", cwd);
            fflush(stdout);
        }
        if (!fgets(line, (int)sizeof(line), stdin))
            break;
        status = run_line(line);
        if (status < 0)
            break;                       /* exit */
        if (status > 0 && interactive)
            printf("[status %d]\n", status);
    }
    return 0;
}
