name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  host-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (host)
        run: make
      - name: Test
        run: make test
